apiVersion: v1
kind: Service
metadata:
  name: web-access
  namespace: thewebguardian
spec: 
  type: NodePort
  selector: 
      app: frontend
      env: prod
  ports:
    - port: 80
      nodePort: 30005